### ISSUE TITLE
Baixar

### ISSUE THREAD

**Issue by Dowjs** [SilvanoGPM/cards-against-humanity#1]
Opa mano, não entendi como baixa o jogo me explica por favor.

**Comment by SilvanoGPM** [comment]
Não é necessário baixar o jogo, apenas acessar por [este link](https://cards-against-humanity-alpha.vercel.app/).

Como utilizamos serviços 100% gratuitos, e o Google ADS não foi aprovado para o site, temos um limite máximo de uso diário, depois que atingido pode ser que o site apresente alguns problemas, como:

- Impossibilidade de criar novas partidas
- Chat das partidas não funcionar
- Tela de login infinita

Infelizmente o número de jogadores diário é maior que nosso limite máximo, e só temos como resolver esses problemas contratando alguns serviços com um limite maior.

O melhor horário para se jogar é das 9h da manhã até as 16h da tarde, poís tem menor fluxo de jogadores.
