### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by geoxeo** [SilvanoGPM/cards-against-humanity#2]
Opa querido! Vim aqui dizer que não dá pra logar com o Google, fica infinitamente carregando. Isso é problema do código ou alguma coisa intereferindo?

**Comment by SilvanoGPM** [comment]
Então, utilizamos serviços 100% gratuitos e temos muitos acessos diários, então geralmente ao final do dia muitas vezes não é possível utilizar a plataforma, o melhor horário para jogar é de manhã cedo.
